### ISSUE TITLE
selenium get location error

### ISSUE THREAD

**Issue by linwei-yoh** [Python3WebSpider/CrackWeiboSlide#2]
经过测试火狐和chrome，在正常模式下全屏截图正常，但是get_image方法获得的截图检查发现位置偏差。
但是都是正常的查找目标元素，获取location。
在headless模式下，get_image方法获得的截图正确，但是move方法执行错误，没能正确实现解锁。
请问能否检查下？我也在查原因但是暂时没找到解决办法

另外目前四宫格个图片都已经更新，都是稍微偏差了1 2个像素的样子。我看看怎么pr下，

**Comment by wadekun** [comment]
@linwei-yoh  兄台已经解决了吗？ 我今天也遇到了这个问题。现在已经解决了：
https://github.com/wadekun/CrackWeiboSlide

结合了 @LiuXingMing 大神的图片裁剪方式。。。

**Comment by linwei-yoh** [comment]
感谢回复 搞定了 3Q
