### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jli113** [Python3WebSpider/CrackWeiboSlide#4]
python crack.py
验证码位置 262 422 445 605
正在匹配 4321.png
正在匹配 3421.png
正在匹配 1324.png
正在匹配 2314.png
正在匹配 1432.png
正在匹配 2341.png
正在匹配 3214.png
正在匹配 4213.png
正在匹配 2431.png
正在匹配 4312.png
正在匹配 3241.png
正在匹配 4123.png
正在匹配 1423.png
正在匹配 2134.png
正在匹配 1234.png
正在匹配 2143.png
正在匹配 1243.png
正在匹配 4231.png
正在匹配 1342.png
正在匹配 2413.png
正在匹配 3412.png
正在匹配 3142.png
正在匹配 4132.png
正在匹配 3124.png
Traceback (most recent call last):
  File "crack.py", line 185, in <module>
    crack.crack()
  File "crack.py", line 178, in crack
    self.move(numbers)
  File "crack.py", line 146, in move
    circle = circles[numbers[index] - 1]
TypeError: 'NoneType' object is not subscriptable

**Comment by wadekun** [comment]
没有匹配到，应该是截图有问题。

**Comment by jli113** [comment]
解决了。
https://github.com/jli113/CrackWeiboSlider
参考：
https://github.com/LiuXingMing/WeiboSliderCode
https://github.com/Python3WebSpider/CrackWeiboSlide
https://blog.csdn.net/bone_ace/article/details/71056741

**Comment by wadekun** [comment]
@jli113 请问你是mac吗。。。我用 LiuXingMing的方式截图也有问题。。。。。

**Comment by jli113** [comment]
不是，centos
